"""add stores table and store_id to products

Revision ID: 98763009b716
Revises: 004_change_avatar_to_text
Create Date: 2026-04-10 18:16:58.328754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98763009b716'
down_revision: Union[str, None] = '004_change_avatar_to_text'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('store_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'store_id')
    # ### end Alembic commands ###
